[tracing]
level = "debug"

[http]
address = "0.0.0.0:3000"

[fflogs]
url = "https://www.fflogs.com/v1/"
# key = "XIVA_FFLOGS_KEY"

[xivapi]
url = "https://beta.xivapi.com/api/1/"

[client]
public_path = "public"
default_branch = "dawntrail"
